package:
  name: tsglm_py
  version: 0.1.0

source:
  path: ..

build:
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - statsmodels

about:
  summary: "Time series forecasting with generalized linear models"
  license: MIT
